Repository AY2425S1-CS2113-W10-2/tp, pull requests merged in 2024-10, with the labels that each got.

#18 Add course information from Australia National University
  data/database.json
Labels: priority.High, severity.High

#19 [Improvement] Add information into database for Victoria University of Wellington
  data/database.json
Labels: type.Task, priority.High, severity.High

#20 Add data for The Uni of Western Australia
  data/database.json
  docs/AboutUs.md
Labels: type.Task, priority.High, severity.High

#23 As a CEG student, I want to list out all the possible schools I can go
  build.gradle
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/exchangecoursemapper/ExchangeCourseMapper.java
  src/main/java/seedu/exchangecoursemapper/command/Command.java
  src/main/java/seedu/exchangecoursemapper/command/ListSchoolCommand.java
  src/main/java/seedu/exchangecoursemapper/exception/Exception.java
  src/main/java/seedu/exchangecoursemapper/parser/Parser.java
  src/main/java/seedu/exchangecoursemapper/storage/Storage.java
  src/main/java/seedu/exchangecoursemapper/ui/UI.java
  src/test/java/seedu/exchangecoursemapper/ExchangeCourseMapperTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Story, priority.High, severity.High

#26 [Feature] Add code for listing commands and refactor welcome message
  src/main/java/seedu/exchangecoursemapper/command/ListCommandsCommand.java
  src/main/java/seedu/exchangecoursemapper/parser/Parser.java
  src/main/java/seedu/exchangecoursemapper/ui/UI.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High, severity.High

#30 [Improvement] Extract constants from code
  src/main/java/seedu/exchangecoursemapper/command/FilterCoursesCommand.java
  src/main/java/seedu/exchangecoursemapper/command/ListUniCoursesCommand.java
  src/main/java/seedu/exchangecoursemapper/constants/Commands.java
  src/main/java/seedu/exchangecoursemapper/constants/JsonKey.java
  src/main/java/seedu/exchangecoursemapper/constants/Messages.java
  src/main/java/seedu/exchangecoursemapper/constants/Regex.java
  src/main/java/seedu/exchangecoursemapper/parser/Parser.java
Labels: priority.Medium, severity.Low

#31 [Feature] Implement add course mapping plan for a PU
  src/main/java/seedu/exchangecoursemapper/command/AddCoursesCommand.java
  src/main/java/seedu/exchangecoursemapper/command/ListCommandsCommand.java
  src/main/java/seedu/exchangecoursemapper/constants/Commands.java
  src/main/java/seedu/exchangecoursemapper/parser/Parser.java
  src/main/java/seedu/exchangecoursemapper/storage/Storage.java
Labels: priority.High, severity.High

#33 [Improvement] Implement J-unit test into test code
  src/test/java/seedu/exchangecoursemapper/ListSchoolCommandTest.java
Labels: type.Enhancement, priority.High, severity.High

#36 [Improvement] Implement JUnit tests for add course mapping
  src/main/java/seedu/exchangecoursemapper/command/AddCoursesCommand.java
  src/test/java/seedu/exchangecoursemapper/AddCoursesCommandTest.java
Labels: priority.High, severity.High

#40 [Improvement] Modify user input parsing in Parser class
  src/main/java/seedu/exchangecoursemapper/constants/Commands.java
  src/main/java/seedu/exchangecoursemapper/constants/Messages.java
  src/main/java/seedu/exchangecoursemapper/parser/Parser.java
  text-ui-test/EXPECTED.TXT
Labels: priority.Medium, severity.High

#41 [Improvement] Implement JUnit tests for listing school courses
  src/test/java/seedu/exchangecoursemapper/ListUniCoursesCommandTest.java
Labels: priority.High, severity.High

#43 Add JUnit tests for listing commands
  src/test/java/seedu/exchangecoursemapper/ListCommandsCommandTest.java
Labels: type.Enhancement, priority.High, severity.High

#46 [Improvement] Implement JUnit tests for filter courses command
  src/main/java/seedu/exchangecoursemapper/command/FilterCoursesCommand.java
  src/main/java/seedu/exchangecoursemapper/constants/Commands.java
  src/main/java/seedu/exchangecoursemapper/constants/Messages.java
  src/main/java/seedu/exchangecoursemapper/exception/Exception.java
  src/main/java/seedu/exchangecoursemapper/exception/ExchangeCourseMapperException.java
  src/test/java/seedu/exchangecoursemapper/FilterCoursesCommandTest.java
Labels: priority.High, severity.High

#47 [Improvement] Add more exceptions for ListUniCoursesCommand
  src/main/java/seedu/exchangecoursemapper/command/ListUniCoursesCommand.java
  src/main/java/seedu/exchangecoursemapper/exception/UnknownUniversityException.java
  src/test/java/seedu/exchangecoursemapper/ListUniCoursesCommandTest.java
Labels: priority.High, severity.High

#49 [BugFix] Fix bugs on list schools
  emptySchools.json
  src/main/java/seedu/exchangecoursemapper/command/AddCoursesCommand.java
  src/main/java/seedu/exchangecoursemapper/command/Command.java
  src/main/java/seedu/exchangecoursemapper/command/FilterCoursesCommand.java
  src/main/java/seedu/exchangecoursemapper/command/ListCommandsCommand.java
  src/main/java/seedu/exchangecoursemapper/command/ListSchoolCommand.java
  src/main/java/seedu/exchangecoursemapper/command/ListUniCoursesCommand.java
  src/main/java/seedu/exchangecoursemapper/constants/Messages.java
  src/main/java/seedu/exchangecoursemapper/exception/Exception.java
  src/main/java/seedu/exchangecoursemapper/parser/Parser.java
  src/main/java/seedu/exchangecoursemapper/ui/UI.java
Labels: type.Bug, priority.Medium, severity.Medium

#51 [Improvement] Include assertions and logging into List Schools for better error handling
  META-INF/MANIFEST.MF
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/seedu/exchangecoursemapper/command/ListSchoolCommand.java
  src/main/java/seedu/exchangecoursemapper/constants/Assertions.java
  src/main/java/seedu/exchangecoursemapper/constants/Logs.java
Labels: type.Task, priority.High, severity.High

#53 [Improvement] Migrate exceptions, include assertions and logging into Filter Courses for better error handling
  src/main/java/seedu/exchangecoursemapper/command/FilterCoursesCommand.java
  src/main/java/seedu/exchangecoursemapper/constants/Assertions.java
  src/main/java/seedu/exchangecoursemapper/constants/Logs.java
  src/main/java/seedu/exchangecoursemapper/constants/Messages.java
  src/main/java/seedu/exchangecoursemapper/exception/Exception.java
  src/test/java/seedu/exchangecoursemapper/FilterCoursesCommandTest.java
Labels: type.Task, priority.High, severity.High

#55 Add logging assertions to ListCommandsCommand and Parser classes
  src/main/java/seedu/exchangecoursemapper/command/ListCommandsCommand.java
  src/main/java/seedu/exchangecoursemapper/constants/Logs.java
  src/main/java/seedu/exchangecoursemapper/parser/Parser.java
Labels: priority.High, severity.High

#57 [Improvement] Add logging and assertion for ListUniCoursesCommand
  src/main/java/seedu/exchangecoursemapper/command/ListUniCoursesCommand.java
  src/main/java/seedu/exchangecoursemapper/constants/Assertions.java
  src/main/java/seedu/exchangecoursemapper/constants/Logs.java
Labels: priority.High, severity.High

#63 [Improvement] Add database as a resource to the JAR file
  src/main/java/seedu/exchangecoursemapper/command/Command.java
  src/main/java/seedu/exchangecoursemapper/command/FilterCoursesCommand.java
  src/main/java/seedu/exchangecoursemapper/command/ListSchoolCommand.java
  src/main/java/seedu/exchangecoursemapper/command/ListUniCoursesCommand.java
  src/main/resources/database.json
Labels: type.Enhancement, priority.Low, severity.Medium

#67 [Improvement] Update the new database with emails and contacts for v2
  data/database.json
  src/main/resources/database.json
Labels: type.Task, priority.High, severity.High

#75 [Improvement] Change storage to store course instead of string
  src/main/java/seedu/exchangecoursemapper/command/AddCoursesCommand.java
  src/main/java/seedu/exchangecoursemapper/courses/Course.java
  src/main/java/seedu/exchangecoursemapper/storage/Storage.java
Labels: type.Enhancement, priority.Medium, severity.High

#72 [Improvement] Add List Schools Command into DG, edit NFR, add on user requirement details
  docs/DeveloperGuide.md
  uml-diagrams/ListSchoolsCommand.puml
  uml-images/ListSchoolsCommand.png
Labels: type.Task, priority.High, severity.High

#78 [Feature] Add code for deleting courses from the personal tracker
  src/main/java/seedu/exchangecoursemapper/ExchangeCourseMapper.java
  src/main/java/seedu/exchangecoursemapper/command/AddCoursesCommand.java
  src/main/java/seedu/exchangecoursemapper/command/DeleteCoursesCommand.java
  src/main/java/seedu/exchangecoursemapper/command/PersonalTrackerCommand.java
  src/main/java/seedu/exchangecoursemapper/constants/Commands.java
  src/main/java/seedu/exchangecoursemapper/exception/Exception.java
  src/main/java/seedu/exchangecoursemapper/parser/Parser.java
  src/main/java/seedu/exchangecoursemapper/storage/Storage.java
  src/main/java/seedu/exchangecoursemapper/ui/UI.java
Labels: type.Story, priority.High, severity.High

#79 [Feature] Implement Obtain Contacts in email and number function for v2.0
  src/main/java/seedu/exchangecoursemapper/command/ListCommandsCommand.java
  src/main/java/seedu/exchangecoursemapper/command/ObtainContactsCommand.java
  src/main/java/seedu/exchangecoursemapper/constants/Commands.java
  src/main/java/seedu/exchangecoursemapper/constants/Regex.java
  src/main/java/seedu/exchangecoursemapper/exception/Exception.java
  src/main/java/seedu/exchangecoursemapper/parser/Parser.java
Labels: type.Story, priority.High, severity.High

#81 [Feature] Implement HelpCommand to show help when required
  src/main/java/seedu/exchangecoursemapper/command/HelpCommand.java
  src/main/java/seedu/exchangecoursemapper/constants/Assertions.java
  src/main/java/seedu/exchangecoursemapper/constants/Commands.java
  src/main/java/seedu/exchangecoursemapper/constants/HelpMessages.java
  src/main/java/seedu/exchangecoursemapper/constants/Logs.java
  src/main/java/seedu/exchangecoursemapper/exception/Exception.java
  src/main/java/seedu/exchangecoursemapper/parser/Parser.java
  src/test/java/seedu/exchangecoursemapper/ListUniCoursesCommandTest.java
Labels: priority.Medium, severity.Medium

#83 [Improvement] Add code to check whether the course mapping added is valid
  src/main/java/seedu/exchangecoursemapper/command/AddCoursesCommand.java
  src/main/java/seedu/exchangecoursemapper/constants/Logs.java
  src/main/java/seedu/exchangecoursemapper/constants/Messages.java
  src/main/java/seedu/exchangecoursemapper/parser/Parser.java
Labels: type.Task, priority.High, severity.High

#87 [Improvement] Implement JUnit tests for filter courses command
  src/main/java/seedu/exchangecoursemapper/command/DeleteCoursesCommand.java
  src/main/java/seedu/exchangecoursemapper/exception/Exception.java
  src/test/java/seedu/exchangecoursemapper/DeleteCoursesCommandTest.java
Labels: type.Task, priority.High, severity.High

#89 [Improvement] Implement JUnit tests for HelpCommand
  src/test/java/seedu/exchangecoursemapper/HelpCommandTest.java
  src/test/java/seedu/exchangecoursemapper/ListUniCoursesCommandTest.java
Labels: priority.High, severity.High

#84 [Improvement] Add Filter Courses Command into DG and user story
  docs/DeveloperGuide.md
  uml-diagrams/FilterCoursesCommand.puml
  uml-images/FilterCoursesCommand.png
Labels: type.Task, priority.High, severity.High

#90 [Improvement] Add error handling into Obtain Contacts Command
  src/main/java/seedu/exchangecoursemapper/command/ObtainContactsCommand.java
  src/main/java/seedu/exchangecoursemapper/constants/Assertions.java
  src/main/java/seedu/exchangecoursemapper/constants/JsonKey.java
  src/test/java/seedu/exchangecoursemapper/ObtainContactsCommandTest.java
Labels: type.Task, priority.High, severity.High

#93 [Feature] Implement save and load feature for myList
  data/myList.json
  src/main/java/seedu/exchangecoursemapper/storage/Storage.java
Labels: type.Epic, priority.Medium, severity.High

#103 [Improvement] Refactor code and add Javadoc to ListUniCoursesCommand
  src/main/java/seedu/exchangecoursemapper/command/ListUniCoursesCommand.java
Labels: priority.High

#100 [Improvement] Document Obtain Contacts into DG, update acknowledgements, user side
  docs/DeveloperGuide.md
  src/main/java/seedu/exchangecoursemapper/command/Command.java
  src/main/java/seedu/exchangecoursemapper/command/ListSchoolCommand.java
  src/main/java/seedu/exchangecoursemapper/command/ObtainContactsCommand.java
  src/main/java/seedu/exchangecoursemapper/constants/Assertions.java
  src/main/java/seedu/exchangecoursemapper/constants/Commands.java
  src/main/java/seedu/exchangecoursemapper/parser/Parser.java
  uml-diagrams/ObtainContactsCommand.puml
  uml-images/ObtainContactsCommand.png
Labels: type.Task, priority.High, severity.High

#104 [Improvement] Add logging and assertions for storage class
  src/main/java/seedu/exchangecoursemapper/command/ListCommandsCommand.java
  src/main/java/seedu/exchangecoursemapper/constants/Messages.java
  src/main/java/seedu/exchangecoursemapper/storage/Storage.java
  src/test/java/seedu/exchangecoursemapper/HelpCommandTest.java
Labels: type.Task, priority.High, severity.High

#106 [Improvement] Conduct error handling for CourseValidator class
  data/myList.json
  src/main/java/seedu/exchangecoursemapper/command/AddCoursesCommand.java
  src/main/java/seedu/exchangecoursemapper/constants/Logs.java
  src/main/java/seedu/exchangecoursemapper/exception/Exception.java
  src/main/java/seedu/exchangecoursemapper/parser/CourseValidator.java
  src/test/java/seedu/exchangecoursemapper/CourseValidatorTest.java
Labels: priority.High, severity.High

#107 [Improvement] Add logging and assertions for DeleteCoursesCommand
  src/main/java/seedu/exchangecoursemapper/command/DeleteCoursesCommand.java
  src/main/java/seedu/exchangecoursemapper/constants/Logs.java
Labels: type.Task, priority.High, severity.High

#109 [Improvement] Add JUnit tests for Storage class
  data/myList.json
  src/main/java/seedu/exchangecoursemapper/storage/Storage.java
  src/test/java/seedu/exchangecoursemapper/StorageTest.java
Labels: type.Task, priority.High, severity.High

#118 [Improvement] Add ListMappedModulesCommand to display all mapped modules
  src/main/java/seedu/exchangecoursemapper/command/ListPersonalTrackerCommand.java
  src/main/java/seedu/exchangecoursemapper/constants/Commands.java
  src/main/java/seedu/exchangecoursemapper/parser/Parser.java
Labels: priority.High, severity.High

#115 [Improvement] Remove Chulalongkorn University across database
  data/database.json
  data/myList.json
  src/main/resources/database.json
  src/test/java/seedu/exchangecoursemapper/DeleteCoursesCommandTest.java
  src/test/java/seedu/exchangecoursemapper/FilterCoursesCommandTest.java
  src/test/java/seedu/exchangecoursemapper/ListSchoolCommandTest.java
  src/test/java/seedu/exchangecoursemapper/ListUniCoursesCommandTest.java
  src/test/java/seedu/exchangecoursemapper/ObtainContactsCommandTest.java
Labels: priority.Low, severity.Low

#116 Refactored test cases for new database
  src/test/java/seedu/exchangecoursemapper/StorageTest.java
Labels: priority.High, severity.High

#120 [Improvement] Better parent child structure for command functions
  docs/DeveloperGuide.md
  src/main/java/seedu/exchangecoursemapper/command/CheckInformationCommand.java
  src/main/java/seedu/exchangecoursemapper/command/Command.java
  src/main/java/seedu/exchangecoursemapper/command/FilterCoursesCommand.java
  src/main/java/seedu/exchangecoursemapper/command/HelpCommand.java
  src/main/java/seedu/exchangecoursemapper/command/ListCommandsCommand.java
  src/main/java/seedu/exchangecoursemapper/command/ListPersonalTrackerCommand.java
  src/main/java/seedu/exchangecoursemapper/command/ListSchoolCommand.java
  src/main/java/seedu/exchangecoursemapper/command/ListUniCoursesCommand.java
  src/main/java/seedu/exchangecoursemapper/command/ObtainContactsCommand.java
  src/main/java/seedu/exchangecoursemapper/command/PersonalTrackerCommand.java
  src/test/java/seedu/exchangecoursemapper/DeleteCoursesCommandTest.java
  src/test/java/seedu/exchangecoursemapper/ObtainContactsCommandTest.java
Labels: type.Enhancement, priority.Low, severity.Low

#122 [Improvement] Modify tests due to changes in database
  src/test/java/seedu/exchangecoursemapper/DeleteCoursesCommandTest.java
  src/test/java/seedu/exchangecoursemapper/FilterCoursesCommandTest.java
Labels: type.Bug, priority.High, severity.High

#124 [Bugfix] Fix J-Unit code for Obtain Contacts and List schools
  data/myList.json
  src/main/java/seedu/exchangecoursemapper/command/ListSchoolCommand.java
  src/test/java/seedu/exchangecoursemapper/ListSchoolCommandTest.java
  src/test/java/seedu/exchangecoursemapper/ObtainContactsCommandTest.java
Labels: type.Bug, priority.High, priority.Medium, severity.Medium

#125 Add CompareMappedModulesCommand with course code-based comparison
  data/myList.json
  src/main/java/seedu/exchangecoursemapper/command/CompareMappedCommand.java
  src/main/java/seedu/exchangecoursemapper/constants/Commands.java
  src/main/java/seedu/exchangecoursemapper/parser/Parser.java
Labels: priority.Medium, severity.High

#134 [Improvement] Add logging and assertions to ListPersonalTrackerCommand
  src/main/java/seedu/exchangecoursemapper/command/ListPersonalTrackerCommand.java
  src/main/java/seedu/exchangecoursemapper/constants/Assertions.java
  src/main/java/seedu/exchangecoursemapper/constants/Logs.java
Labels: type.Task, priority.Medium, severity.Medium

#112 [Improvement] Update Developer Guide with AddCoursesCommand
  docs/DeveloperGuide.md
  uml-diagrams/AddCoursesCommand.puml
  uml-images/AddCoursesCommand.png
Labels: type.Task, priority.High, severity.High

#147 [Improvement] Add javadocs for better documentation and extract UI methods into UI class
  src/main/java/seedu/exchangecoursemapper/command/AddCoursesCommand.java
  src/main/java/seedu/exchangecoursemapper/constants/Assertions.java
  src/main/java/seedu/exchangecoursemapper/parser/CourseValidator.java
  src/main/java/seedu/exchangecoursemapper/ui/UI.java
Labels: type.Task, priority.Medium, severity.Low

#110 [Improvement] Add ListUniCoursesCommand into DG
  docs/DeveloperGuide.md
  uml-diagrams/ListUniCoursesCommand.puml
  uml-images/ListUniCoursesCommand.png
Labels: priority.High, severity.High

#149 [Improvement] FilterCourses and DeleteCourses: Add JavaDocs and extract UI methods into UI class
  src/main/java/seedu/exchangecoursemapper/command/DeleteCoursesCommand.java
  src/main/java/seedu/exchangecoursemapper/command/FilterCoursesCommand.java
  src/main/java/seedu/exchangecoursemapper/command/ListPersonalTrackerCommand.java
  src/main/java/seedu/exchangecoursemapper/constants/Messages.java
  src/main/java/seedu/exchangecoursemapper/ui/UI.java
Labels: type.Enhancement, priority.High, severity.High

#148 [Improvement] Add Javadoc for HelpCommand and update JUnit test for ListUniCoursesCommand
  src/main/java/seedu/exchangecoursemapper/command/HelpCommand.java
  src/main/java/seedu/exchangecoursemapper/constants/HelpMessages.java
  src/main/java/seedu/exchangecoursemapper/constants/Messages.java
  src/test/java/seedu/exchangecoursemapper/HelpCommandTest.java
  src/test/java/seedu/exchangecoursemapper/ListUniCoursesCommandTest.java
Labels: priority.High, severity.High

#139 [Improvement] Add logging, assertions, and constants to CompareMappedCommand
  src/main/java/seedu/exchangecoursemapper/command/CompareMappedCommand.java
  src/main/java/seedu/exchangecoursemapper/command/ListPersonalTrackerCommand.java
  src/main/java/seedu/exchangecoursemapper/constants/Assertions.java
  src/main/java/seedu/exchangecoursemapper/constants/Logs.java
  src/main/java/seedu/exchangecoursemapper/constants/Messages.java
Labels: type.Task, priority.Medium, severity.Medium

#158 [Bug Fix] Add error handling to FilterCoursesCommand
  src/main/java/seedu/exchangecoursemapper/command/FilterCoursesCommand.java
  src/test/java/seedu/exchangecoursemapper/FilterCoursesCommandTest.java
Labels: type.Bug, priority.High, severity.High

#156 [Improvement] Architecture diagram for DG design section
  data/myList.json
  docs/DeveloperGuide.md
  uml-diagrams/ArchitectureDiagram.puml
  uml-diagrams/DesignSequenceDiagram.puml
  uml-diagrams/MiniCommandClass.puml
  uml-images/ArchitectureDiagram.png
  uml-images/DesignSequenceDiagram.png
  uml-images/MiniCommandClass.png
Labels: type.Task, priority.Medium, severity.Medium

#135 [Improvement] Class diagram for the command package
  docs/DeveloperGuide.md
  src/main/java/seedu/exchangecoursemapper/command/Command.java
  src/main/java/seedu/exchangecoursemapper/command/ListPersonalTrackerCommand.java
  src/main/java/seedu/exchangecoursemapper/constants/Commands.java
  src/main/java/seedu/exchangecoursemapper/parser/Parser.java
  uml-diagrams/CommandClass.puml
  uml-images/CommandClass.png
Labels: type.Task, priority.High

#162 [BugFix] Change file structure of images and diagram for Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/AddCoursesCommand.puml
  docs/diagrams/ArchitectureDiagram.puml
  docs/diagrams/CommandClass.puml
  docs/diagrams/DesignSequenceDiagram.puml
  docs/diagrams/FilterCoursesCommand.puml
  docs/diagrams/ListSchoolsCommand.puml
  docs/diagrams/ListUniCoursesCommand.puml
  docs/diagrams/MiniCommandClass.puml
  docs/diagrams/ObtainContactsCommand.puml
  docs/images/AddCoursesCommand.png
  docs/images/ArchitectureDiagram.png
  docs/images/CommandClass.png
  docs/images/DesignSequenceDiagram.png
  docs/images/FilterCoursesCommand.png
  docs/images/ListSchoolsCommand.png
  docs/images/ListUniCoursesCommand.png
  docs/images/MiniCommandClass.png
  docs/images/ObtainContactsCommand.png
Labels: type.Bug, priority.Low, severity.High

#167 [Improvement] Add JavaDoc header comments to non-trivial methods in List Schools and Obtain Contacts
  src/main/java/seedu/exchangecoursemapper/command/CheckInformationCommand.java
  src/main/java/seedu/exchangecoursemapper/command/Command.java
  src/main/java/seedu/exchangecoursemapper/command/ListSchoolCommand.java
  src/main/java/seedu/exchangecoursemapper/command/ObtainContactsCommand.java
  src/main/java/seedu/exchangecoursemapper/command/PersonalTrackerCommand.java
  src/main/java/seedu/exchangecoursemapper/ui/UI.java
Labels: type.Enhancement, priority.Low, severity.Low

#166 [Improvement] Fix ListUniCoursesCommand bug and extract methods in ListUniCoursesCommand to UI class
  src/main/java/seedu/exchangecoursemapper/command/ListUniCoursesCommand.java
  src/main/java/seedu/exchangecoursemapper/constants/Logs.java
  src/main/java/seedu/exchangecoursemapper/ui/UI.java
  src/test/java/seedu/exchangecoursemapper/ListUniCoursesCommandTest.java
Labels: priority.High, severity.High

#168 Update developer guide with details for ListCommandsCommand and ListPersonalTrackerCommand
  docs/DeveloperGuide.md
  uml-diagrams/ListCommandsCommand.puml
  uml-diagrams/ListPersonalTrackerCommand.puml
  uml-images/ListCommandsCommand.png
  uml-images/ListPersonalTrackerCommand.png
Labels: type.Task, priority.High, severity.High

#173 Update ppp first draft for week 11
  docs/AboutUs.md
  docs/README.md
  docs/UserGuide.md
  docs/team/louisjoety.md
Labels: type.Task, priority.High, severity.Low
