Repository AY2425S1-CS2113-W10-2/tp, pull requests merged in 2024-11, with the labels that each got.

#184 Draft PPP for week 11 submission
  docs/team/hzxnancy.md
Labels: type.Task, priority.High, severity.Low, severity.High

#181 [Improvement] Add config file for sequence diagrams to follow standard notations
  docs/diagrams/.SequenceDiagram.config
  docs/diagrams/DeleteCoursesCommand.puml
  docs/images/DeleteCoursesCommand.png
Labels: type.Task, type.Bug, priority.High

#179 [Improvement] Add config file for class diagrams to follow standard notations
  docs/diagrams/.ClassDiagram.config
  docs/diagrams/CommandClass.puml
  docs/images/CommandClass.png
Labels: type.Task, type.Bug, priority.High

#185 Draft PPP for week 11 task
  docs/team/chiang-huixin.md
Labels: type.Task, priority.High

#169 [Improvement] Update Developer Guide with CourseValidator class diagram
  docs/DeveloperGuide.md
  docs/diagrams/CourseValidatorClass.puml
  docs/images/CourseValidatorClass.png
  src/main/java/seedu/exchangecoursemapper/constants/Messages.java
  src/main/java/seedu/exchangecoursemapper/parser/CourseValidator.java
Labels: type.Enhancement, priority.High, severity.High

#187 Draft PPP for week 11 task
  docs/team/chewycj.md
Labels: type.Task, priority.High

#188 [Improvement] Update UG with filtercourses and deletecourses
  docs/UserGuide.md
Labels: type.Task, priority.High, severity.High

#192 Urgent PR to: Make a note to self on TODOs in UG
  docs/UserGuide.md
Labels: priority.High, severity.Low

#170 [Improvement] Update DG for HelpCommands and ListUniCoursesCommand
  docs/DeveloperGuide.md
  docs/diagrams/HelpCommand.puml
  docs/diagrams/ListUniCoursesCommand.puml
  docs/images/HelpCommand.png
Labels: priority.High, severity.High

#178 [Improvement] Add JUnit tests for ListPersonalTrackerCommand and CompareMappedCommand
  data/myList.json
  src/test/java/seedu/exchangecoursemapper/CompareMappedCommandTest.java
  src/test/java/seedu/exchangecoursemapper/ListPersonalTrackerCommandTest.java
Labels: type.Task, priority.High, severity.High

#194 Update UG with AddCoursesCommand
  docs/UserGuide.md
  src/main/java/seedu/exchangecoursemapper/constants/Messages.java
  src/main/java/seedu/exchangecoursemapper/ui/UI.java
Labels: type.Task, priority.High, severity.Low

#198 [improvement] Refactored commands to include UI class
  src/main/java/seedu/exchangecoursemapper/command/CompareMappedCommand.java
  src/main/java/seedu/exchangecoursemapper/command/ListCommandsCommand.java
  src/main/java/seedu/exchangecoursemapper/command/ListPersonalTrackerCommand.java
  src/main/java/seedu/exchangecoursemapper/constants/Assertions.java
  src/main/java/seedu/exchangecoursemapper/constants/Logs.java
  src/main/java/seedu/exchangecoursemapper/constants/Messages.java
  src/main/java/seedu/exchangecoursemapper/ui/UI.java
Labels: priority.High, severity.High

#199 [Improvement] Refactor printing output to UI class
  src/main/java/seedu/exchangecoursemapper/command/Command.java
  src/main/java/seedu/exchangecoursemapper/command/ListSchoolCommand.java
  src/main/java/seedu/exchangecoursemapper/command/ObtainContactsCommand.java
  src/main/java/seedu/exchangecoursemapper/constants/Logs.java
  src/main/java/seedu/exchangecoursemapper/constants/Messages.java
  src/main/java/seedu/exchangecoursemapper/ui/UI.java
  src/test/java/seedu/exchangecoursemapper/ObtainContactsCommandTest.java
Labels: type.Task, priority.Low, severity.Low

#203 [Improvement] Draft UG for v1 and v2, Add some FAQ, Add backbone of command summary
  docs/UserGuide.md
  src/main/java/seedu/exchangecoursemapper/constants/Messages.java
Labels: type.Task, priority.Low, severity.Medium

#201 Update DG for CompareMappedCommand
  docs/DeveloperGuide.md
  docs/diagrams/CompareMappedCommand.puml
  docs/diagrams/ListCommandsCommand.puml
  docs/diagrams/ListPersonalTrackerCommand.puml
  docs/images/CompareMappedCommand.png
  docs/images/ListCommandsCommand.png
  docs/images/ListPersonalTrackerCommand.png
Labels: type.Task, priority.High, severity.High

#209 Refactored Storage Class and added loading validation
  src/main/java/seedu/exchangecoursemapper/command/AddCoursesCommand.java
  src/main/java/seedu/exchangecoursemapper/command/CompareMappedCommand.java
  src/main/java/seedu/exchangecoursemapper/command/DeleteCoursesCommand.java
  src/main/java/seedu/exchangecoursemapper/command/ListPersonalTrackerCommand.java
  src/main/java/seedu/exchangecoursemapper/constants/Assertions.java
  src/main/java/seedu/exchangecoursemapper/constants/Logs.java
  src/main/java/seedu/exchangecoursemapper/constants/Messages.java
  src/main/java/seedu/exchangecoursemapper/storage/CourseFormatter.java
  src/main/java/seedu/exchangecoursemapper/storage/CourseRepository.java
  src/main/java/seedu/exchangecoursemapper/storage/DataIntegrityChecker.java
  src/main/java/seedu/exchangecoursemapper/storage/FileHandler.java
  src/main/java/seedu/exchangecoursemapper/storage/Storage.java
  src/main/java/seedu/exchangecoursemapper/ui/UI.java
  src/test/java/seedu/exchangecoursemapper/CompareMappedCommandTest.java
  src/test/java/seedu/exchangecoursemapper/ListPersonalTrackerCommandTest.java
  src/test/java/seedu/exchangecoursemapper/StorageTest.java
Labels: type.Task, priority.High, severity.High

#216 [Improvement] Fix bugs and implement OOP in FilterCourses and DeleteCourses
  src/main/java/seedu/exchangecoursemapper/command/CheckInformationCommand.java
  src/main/java/seedu/exchangecoursemapper/command/Command.java
  src/main/java/seedu/exchangecoursemapper/command/DeleteCoursesCommand.java
  src/main/java/seedu/exchangecoursemapper/command/FilterCoursesCommand.java
  src/main/java/seedu/exchangecoursemapper/command/PersonalTrackerCommand.java
  src/main/java/seedu/exchangecoursemapper/constants/Messages.java
  src/main/java/seedu/exchangecoursemapper/exception/Exception.java
  src/main/java/seedu/exchangecoursemapper/exception/ExchangeCourseMapperException.java
  src/main/java/seedu/exchangecoursemapper/ui/UI.java
  src/test/java/seedu/exchangecoursemapper/DeleteCoursesCommandTest.java
  src/test/java/seedu/exchangecoursemapper/FilterCoursesCommandTest.java
Labels: type.Task, priority.High, severity.High

#214 [Feature] Implement FindCoursesCommand
  src/main/java/seedu/exchangecoursemapper/command/FindCoursesCommand.java
  src/main/java/seedu/exchangecoursemapper/command/HelpCommand.java
  src/main/java/seedu/exchangecoursemapper/command/ListUniCoursesCommand.java
  src/main/java/seedu/exchangecoursemapper/constants/Assertions.java
  src/main/java/seedu/exchangecoursemapper/constants/Logs.java
  src/main/java/seedu/exchangecoursemapper/exception/Exception.java
  src/main/java/seedu/exchangecoursemapper/parser/Parser.java
  src/main/java/seedu/exchangecoursemapper/ui/UI.java
  src/test/java/seedu/exchangecoursemapper/FindCoursesCommandTest.java
  src/test/java/seedu/exchangecoursemapper/HelpCommandTest.java
  src/test/java/seedu/exchangecoursemapper/ListUniCoursesCommandTest.java
Labels: priority.High, severity.High

#224 [Improvement] Update manual testing in DG for start state and CheckInformationCommands
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Task, priority.High

#205 [Improvement] Improve readability and notations used in command class diagrams
  docs/DeveloperGuide.md
  docs/diagrams/CheckInformationCommandClass.puml
  docs/diagrams/CommandClassInheritance.puml
  docs/diagrams/CourseValidatorClass.puml
  docs/diagrams/PersonalTrackerCommandClass.puml
  docs/images/CheckInformationCommandClass.jpg
  docs/images/CheckInformationCommandClass.png
  docs/images/CommandClassInheritance.png
  docs/images/CourseValidatorClass.png
  docs/images/PersonalTrackerCommandClass.jpg
  docs/images/PersonalTrackerCommandClass.png
Labels: type.Task, type.Bug, priority.High

#229 [Improvement] Update manual guide for AddCoursesCommand, DeleteCoursesCommand and FindCoursesCommand
  docs/DeveloperGuide.md
Labels: priority.High

#223 Update DG, UG and PPP for v2.0
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddCoursesCommand.puml
  docs/diagrams/CourseValidator.puml
  docs/diagrams/CourseValidatorClass.puml
  docs/images/AddCoursesCommand.png
  docs/images/CourseValidator.png
  docs/images/CourseValidatorClass.png
  docs/team/hzxnancy.md
Labels: type.Task, priority.High, severity.Medium

#219 [Improvement] Update DG and UG for FindCoursesCommand
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/FindCoursesCommand.puml
  docs/diagrams/HelpCommand.puml
  docs/diagrams/ListUniCoursesCommand.puml
  docs/images/FindCoursesCommand.png
  docs/images/HelpCommand.png
  docs/images/ListUniCoursesCommand.png
Labels: priority.High, priority.Medium

#220 [Improvement] Update documentation based on given feedback
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ArchitectureDiagram.puml
  docs/diagrams/DesignSequenceDiagram.puml
  docs/diagrams/ListSchoolsCommand.puml
  docs/diagrams/MiniCommandClass.puml
  docs/diagrams/ObtainContactsCommand.puml
  docs/images/ArchitectureDiagram.png
  docs/images/DesignSequenceDiagram.png
  docs/images/ListSchoolsCommand.png
  docs/images/MiniCommandClass.png
  docs/images/ObtainContactsCommand.png
  docs/team/ObtainContactsCommand.png
  src/main/java/seedu/exchangecoursemapper/command/CompareMappedCommand.java
  src/main/java/seedu/exchangecoursemapper/command/HelpCommand.java
  src/main/java/seedu/exchangecoursemapper/command/ListSchoolCommand.java
  src/main/java/seedu/exchangecoursemapper/command/ObtainContactsCommand.java
  src/main/java/seedu/exchangecoursemapper/constants/HelpMessages.java
  src/main/java/seedu/exchangecoursemapper/constants/Logs.java
  src/main/java/seedu/exchangecoursemapper/constants/Messages.java
  src/main/java/seedu/exchangecoursemapper/storage/DataIntegrityChecker.java
  src/test/java/seedu/exchangecoursemapper/ListPersonalTrackerCommandTest.java
Labels: type.Task, priority.Medium, severity.Medium

#231 [Improvement] Change the order of the UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Enhancement, priority.Low, severity.Low

#233 [Improvement] Change the order of UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.Low, severity.Low

#235 [Improvement] Update order of commands in DG and UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/FilterCoursesCommand.puml
  src/main/java/seedu/exchangecoursemapper/command/FilterCoursesCommand.java
Labels: type.Task, priority.High

#238 Removed CourseFormatter, moved mehods in to Course class for better SOP
  src/main/java/seedu/exchangecoursemapper/courses/Course.java
  src/main/java/seedu/exchangecoursemapper/storage/CourseFormatter.java
  src/main/java/seedu/exchangecoursemapper/storage/CourseRepository.java
  src/main/java/seedu/exchangecoursemapper/storage/DataIntegrityChecker.java
Labels: type.Task, priority.Low, severity.Low

#172 [Improvement] Implement Parser class diagram into DG
  docs/DeveloperGuide.md
  docs/diagrams/CheckInformationParserClass.puml
  docs/diagrams/FindCoursesCommand.puml
  docs/diagrams/HelpCommand.puml
  docs/diagrams/ListUniCoursesCommand.puml
  docs/diagrams/PersonalTrackerParserClass.puml
  docs/diagrams/UIClass.puml
  docs/images/CheckInformationParserClass.png
  docs/images/FindCoursesCommand.png
  docs/images/HelpCommand.png
  docs/images/ListUniCoursesCommand.png
  docs/images/PersonalTrackerParserClass.png
  src/main/java/seedu/exchangecoursemapper/constants/Commands.java
  src/main/java/seedu/exchangecoursemapper/constants/HelpMessages.java
  src/main/java/seedu/exchangecoursemapper/parser/Parser.java
Labels: priority.Medium, severity.Low

#241 [Improvement] Pull Out repeated commands section
  docs/DeveloperGuide.md
  docs/diagrams/CommandFileRead.puml
  docs/images/CommandFileRead.png
Labels: priority.Low, severity.Low

#243 [Improvement] Improve documentation of filter and delete commands
  docs/DeveloperGuide.md
  docs/diagrams/DeleteCoursesCommand.puml
  docs/diagrams/FilterCoursesCommand.puml
  docs/diagrams/PersonalTrackerCommandClass.puml
  docs/images/DeleteCoursesCommand.png
  docs/images/FilterCoursesCommand.png
  docs/images/PersonalTrackerCommandClass.jpg
  docs/team/chewycj.md
  src/main/java/seedu/exchangecoursemapper/command/DeleteCoursesCommand.java
  src/main/java/seedu/exchangecoursemapper/constants/Logs.java
  src/main/java/seedu/exchangecoursemapper/exception/Exception.java
  src/main/java/seedu/exchangecoursemapper/parser/Parser.java
  src/test/java/seedu/exchangecoursemapper/DeleteCoursesCommandTest.java
Labels: type.Task, priority.High

#247 [Improvement] Remove exception on SD, Refactor PPP
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/CommandFileRead.puml
  docs/diagrams/ListSchoolsCommand.puml
  docs/diagrams/ObtainContactsCommand.puml
  docs/images/CommandFileRead.png
  docs/images/ListSchoolsCommand.png
  docs/images/ObtainContactsCommand.png
  docs/team/ObtainContactsCommand.png
  docs/team/louisjoety.md
  src/main/java/seedu/exchangecoursemapper/command/ListSchoolCommand.java
  src/main/java/seedu/exchangecoursemapper/command/ObtainContactsCommand.java
  src/main/java/seedu/exchangecoursemapper/constants/Commands.java
  src/main/java/seedu/exchangecoursemapper/constants/Messages.java
  src/test/java/seedu/exchangecoursemapper/ObtainContactsCommandTest.java
Labels: type.Task, priority.High, severity.High

#249 [Improvement] Fix formatting and bugs in DG and UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/SuccessfulDeleteMessage.png
Labels: type.Task, type.Bug, priority.High

#250 Add Coursevalidator to CompareMappedCommand and ListPersonalTrackerCommand for DG
  docs/DeveloperGuide.md
  docs/diagrams/CompareMappedCommand.puml
  docs/diagrams/ListPersonalTrackerCommand.puml
  docs/images/CompareMappedCommand.png
  docs/images/ListPersonalTrackerCommand.png
Labels: type.Task, priority.High, priority.Low, severity.Low

#253 [Bug Fix] DeleteCoursesCommand index offset and FilterCourses sequence diagram
  docs/diagrams/FilterCoursesCommand.puml
  docs/images/FilterCoursesCommand.png
  src/main/java/seedu/exchangecoursemapper/command/DeleteCoursesCommand.java
Labels: type.Bug, priority.High

#254 [Improvement] General Housekeeping of Documentation
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/louisjoety.md
Labels: type.Task, priority.Low, severity.Low

#259 [Bug Fix] Parsing of commands that do not require additional user input
  src/main/java/seedu/exchangecoursemapper/parser/Parser.java
Labels: type.Bug, priority.Medium

#261 [Improvement] Add documentation regarding storage location and warnings
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Enhancement, priority.Medium, severity.Medium

#262 Refactor test case for ListCommandsCommandTest and ListPersonalTrackerCommandTest
  src/test/java/seedu/exchangecoursemapper/ListCommandsCommandTest.java
  src/test/java/seedu/exchangecoursemapper/ListPersonalTrackerCommandTest.java
Labels: type.Task, priority.Low, severity.Low

#263 Refactored expected output for ListCommandsCommand for UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/ListCommandsCommandMessage.png
Labels: type.Task, priority.Low, severity.Low

#264 [Improvement] Update DG with details for deletecourses
  docs/DeveloperGuide.md
Labels: type.Task, priority.Medium

#265 Refactor CompareCommand to accept lowercase universities
  src/main/java/seedu/exchangecoursemapper/command/CompareMappedCommand.java
  src/test/java/seedu/exchangecoursemapper/CompareMappedCommandTest.java
Labels: priority.Low, severity.Low

#314 [Bug Fix] Provide more detailed guidance to user for the filter command and update documentation with newest details
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/exchangecoursemapper/command/DeleteCoursesCommand.java
  src/main/java/seedu/exchangecoursemapper/command/FilterCoursesCommand.java
  src/main/java/seedu/exchangecoursemapper/constants/Messages.java
  src/main/java/seedu/exchangecoursemapper/constants/Regex.java
  src/main/java/seedu/exchangecoursemapper/exception/Exception.java
  src/main/java/seedu/exchangecoursemapper/parser/NusCourseCodeValidator.java
  src/main/java/seedu/exchangecoursemapper/ui/UI.java
  src/test/java/seedu/exchangecoursemapper/FilterCoursesCommandTest.java
  src/test/java/seedu/exchangecoursemapper/NusCourseCodeValidatorTest.java
Labels: type.Bug, priority.High, severity.Medium

#315 Add method to parse university abbreviations
  data/myList.json
  src/main/java/seedu/exchangecoursemapper/ExchangeCourseMapper.java
  src/main/java/seedu/exchangecoursemapper/command/AddCoursesCommand.java
  src/main/java/seedu/exchangecoursemapper/constants/Logs.java
  src/main/java/seedu/exchangecoursemapper/constants/Messages.java
  src/main/java/seedu/exchangecoursemapper/parser/Parser.java
Labels: type.Enhancement, priority.High, severity.High

#320 [Bug Fix] Documentation: Apply standard notations to command class diagrams
  docs/DeveloperGuide.md
  docs/diagrams/CheckInformationCommandClass.puml
  docs/images/CheckInformationCommandClass.jpg
  docs/images/CommandClassInheritance.jpg
  docs/images/PersonalTrackerCommandClass.jpg
Labels: type.Bug, priority.Medium, severity.Low

#319 [Bug Fix] Exception handling in Filter and delete commands
  data/myList.json
  src/main/java/seedu/exchangecoursemapper/constants/Commands.java
  src/main/java/seedu/exchangecoursemapper/exception/Exception.java
  src/main/java/seedu/exchangecoursemapper/parser/NusCourseCodeValidator.java
  src/test/java/seedu/exchangecoursemapper/DeleteCoursesCommandTest.java
  src/test/java/seedu/exchangecoursemapper/FilterCoursesCommandTest.java
Labels: type.Bug, priority.Medium, severity.Medium

#322 [Improvement] Work on feedback from PED and Refactor Obtain Contacts
  data/myList.json
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ObtainContactsCommand.puml
  docs/images/ObtainContactsCommand.png
  docs/images/SmallCommandClass.png
  src/main/java/seedu/exchangecoursemapper/ExchangeCourseMapper.java
  src/main/java/seedu/exchangecoursemapper/command/ListSchoolCommand.java
  src/main/java/seedu/exchangecoursemapper/command/ObtainContactsCommand.java
  src/main/java/seedu/exchangecoursemapper/parser/Parser.java
  src/main/java/seedu/exchangecoursemapper/parser/SchoolContactValidator.java
  src/test/java/seedu/exchangecoursemapper/ListSchoolCommandTest.java
  src/test/java/seedu/exchangecoursemapper/ObtainContactsCommandTest.java
  src/test/java/seedu/exchangecoursemapper/ParserTest.java
Labels: type.Enhancement, priority.High, severity.Medium

#323 Refactor UG and UI based on PED comments
  docs/UserGuide.md
  src/main/java/seedu/exchangecoursemapper/constants/Messages.java
  src/main/java/seedu/exchangecoursemapper/ui/UI.java
  src/test/java/seedu/exchangecoursemapper/ListCommandsCommandTest.java
  src/test/java/seedu/exchangecoursemapper/ListPersonalTrackerCommandTest.java
Labels: type.Task, priority.Low, severity.Low

#325 [BugFix] Remove [NBSP] tag from database
  data/database.json
  src/main/resources/database.json
  src/test/java/seedu/exchangecoursemapper/AddCoursesCommandTest.java
Labels: type.Bug, priority.High, severity.High

#327 [Improvement] Update documentations based on newest changes
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/DeleteCoursesCommand.puml
  docs/diagrams/FilterCoursesCommand.puml
  docs/images/CheckInformationCommandClass.jpg
  docs/images/DeleteCoursesCommand.png
  docs/images/FilterCoursesCommand.png
  docs/images/PersonalTrackerCommandClass.jpg
  docs/team/chewycj.md
  src/main/java/seedu/exchangecoursemapper/command/DeleteCoursesCommand.java
  src/main/java/seedu/exchangecoursemapper/command/FilterCoursesCommand.java
  src/main/java/seedu/exchangecoursemapper/constants/Commands.java
Labels: type.Task, priority.High, severity.Medium

#331 Add duplicate entry checker to remove duplicates and save unique courses
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/CompareMappedCommand.puml
  docs/diagrams/ListPersonalTrackerCommand.puml
  docs/images/CompareMappedCommand.png
  docs/images/ListPersonalTrackerCommand.png
  src/main/java/seedu/exchangecoursemapper/command/AddCoursesCommand.java
  src/main/java/seedu/exchangecoursemapper/command/CompareMappedCommand.java
  src/main/java/seedu/exchangecoursemapper/command/DeleteCoursesCommand.java
  src/main/java/seedu/exchangecoursemapper/command/FindCoursesCommand.java
  src/main/java/seedu/exchangecoursemapper/command/ListPersonalTrackerCommand.java
  src/main/java/seedu/exchangecoursemapper/constants/Messages.java
  src/main/java/seedu/exchangecoursemapper/storage/CourseRepository.java
  src/main/java/seedu/exchangecoursemapper/storage/DataIntegrityChecker.java
  src/main/java/seedu/exchangecoursemapper/storage/Storage.java
  src/main/java/seedu/exchangecoursemapper/ui/UI.java
Labels: type.Task, priority.Medium, severity.Medium

#330 [Improvement] Fix bugs for V2.1 and change keyword "set" to "list courses"
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/exchangecoursemapper/command/FindCoursesCommand.java
  src/main/java/seedu/exchangecoursemapper/command/HelpCommand.java
  src/main/java/seedu/exchangecoursemapper/command/ListUniCoursesCommand.java
  src/main/java/seedu/exchangecoursemapper/constants/Commands.java
  src/main/java/seedu/exchangecoursemapper/constants/HelpMessages.java
  src/main/java/seedu/exchangecoursemapper/constants/Messages.java
  src/main/java/seedu/exchangecoursemapper/parser/Parser.java
  src/main/java/seedu/exchangecoursemapper/ui/UI.java
  src/test/java/seedu/exchangecoursemapper/HelpCommandTest.java
  src/test/java/seedu/exchangecoursemapper/ListCommandsCommandTest.java
  src/test/java/seedu/exchangecoursemapper/ListUniCoursesCommandTest.java
  src/test/java/seedu/exchangecoursemapper/ParserTest.java
Labels: type.Bug, priority.High, severity.High

#334 [BigFix] Change casing for abbreviations
  src/main/java/seedu/exchangecoursemapper/constants/Logs.java
  src/test/java/seedu/exchangecoursemapper/ParserTest.java
Labels: type.Bug, priority.Medium, severity.Medium

#338 [Improvement] Add DataIntegrityCheckerTest and refactor CompareMappedCommand to accept abbreviations
  src/main/java/seedu/exchangecoursemapper/command/CompareMappedCommand.java
  src/test/java/seedu/exchangecoursemapper/DataIntegrityCheckerTest.java
Labels: type.Task, priority.Medium, severity.Low

#339 [Improvement]Ppp Update, update code to match latest version
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ListSchoolsCommand.puml
  docs/diagrams/ObtainContactsCommand.puml
  docs/images/ListSchoolsCommand.png
  docs/images/ObtainContactsCommand.png
  docs/team/louisjoety.md
  src/main/java/seedu/exchangecoursemapper/command/ListSchoolCommand.java
  src/main/java/seedu/exchangecoursemapper/command/ObtainContactsCommand.java
  src/main/java/seedu/exchangecoursemapper/constants/Commands.java
  src/main/java/seedu/exchangecoursemapper/constants/Logs.java
  src/main/java/seedu/exchangecoursemapper/constants/Messages.java
  src/main/java/seedu/exchangecoursemapper/constants/Regex.java
  src/main/java/seedu/exchangecoursemapper/parser/SchoolContactValidator.java
  src/test/java/seedu/exchangecoursemapper/ListSchoolCommandTest.java
  src/test/java/seedu/exchangecoursemapper/ObtainContactsCommandTest.java
  src/test/java/seedu/exchangecoursemapper/ParserTest.java
Labels: type.Bug, priority.Medium, severity.Medium

#344 [Improvement] Update documentations and PPP based on new code
  docs/DeveloperGuide.md
  docs/team/chewycj.md
Labels: type.Task, type.Bug, priority.Medium

#345 Added checker to add command to prevent addition of duplicate entries
  src/main/java/seedu/exchangecoursemapper/command/AddCoursesCommand.java
  src/main/java/seedu/exchangecoursemapper/command/CompareMappedCommand.java
  src/main/java/seedu/exchangecoursemapper/command/DeleteCoursesCommand.java
  src/main/java/seedu/exchangecoursemapper/command/FindCoursesCommand.java
  src/main/java/seedu/exchangecoursemapper/command/ListPersonalTrackerCommand.java
  src/main/java/seedu/exchangecoursemapper/constants/Messages.java
  src/main/java/seedu/exchangecoursemapper/courses/Course.java
  src/main/java/seedu/exchangecoursemapper/storage/CourseRepository.java
  src/main/java/seedu/exchangecoursemapper/storage/DataIntegrityChecker.java
  src/main/java/seedu/exchangecoursemapper/ui/UI.java
  src/test/java/seedu/exchangecoursemapper/DataIntegrityCheckerTest.java
Labels: type.Task, priority.Medium, severity.Medium

#347 [Improvement] Update Sequence diagram for ListUniCoursesCommand and FindCoursesCommand
  docs/diagrams/FindCoursesCommand.puml
  docs/diagrams/ListUniCoursesCommand.puml
  docs/images/FindCoursesCommand.png
  docs/images/ListUniCoursesCommand.png
  docs/team/chiang-huixin.md
  src/main/java/seedu/exchangecoursemapper/command/HelpCommand.java
  src/main/java/seedu/exchangecoursemapper/command/ListUniCoursesCommand.java
Labels: priority.High, severity.Low

#350 [Improvement] Add loggings to new parts of code, and update PPP
  docs/team/chewycj.md
  src/main/java/seedu/exchangecoursemapper/command/DeleteCoursesCommand.java
  src/main/java/seedu/exchangecoursemapper/command/FilterCoursesCommand.java
  src/main/java/seedu/exchangecoursemapper/constants/Logs.java
Labels: type.Task, priority.Medium, severity.Medium

#352 [Improvement] Update Parser Class diagram for DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/CheckInformationParserClass.jpg
  docs/images/CheckInformationParserClass.png
  docs/images/PersonalTrackerParserClass.jpg
  docs/images/PersonalTrackerParserClass.png
Labels: priority.High, severity.Low

#353 [Improvement] Fix typos and PPP overflow in PDF
  data/myList.json
  docs/UserGuide.md
  docs/team/louisjoety.md
  src/main/java/seedu/exchangecoursemapper/command/ListSchoolCommand.java
Labels: priority.Medium

#354 [Improvement] Refactor and shorten PPP
  docs/team/chiang-huixin.md
Labels: severity.Low

#356 [Improvement] Update PPP, DG and UG after v2.1
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddCoursesCommand.puml
  docs/diagrams/CourseValidator.puml
  docs/images/AddCoursesCommand.png
  docs/images/CourseValidator.png
  docs/team/hzxnancy.md
Labels: type.Enhancement, priority.Medium, severity.Medium

#358 [Improvement] Shorten PPP and resize FindCoursesCommand sequence diagram
  docs/UserGuide.md
  docs/images/FindCoursesCommand.png
  docs/team/chiang-huixin.md
Labels: priority.High

#359 Refactored diagrams and added javadocs ListPersonalTrackerCommand and CompareMappedCommand
  docs/UserGuide.md
  docs/diagrams/ListCommandsCommand.puml
  docs/images/CompareMappedCommand.png
  docs/images/ListCommandsCommand.png
  docs/images/ListPersonalTrackerCommand.png
  src/main/java/seedu/exchangecoursemapper/command/CompareMappedCommand.java
  src/main/java/seedu/exchangecoursemapper/command/ListCommandsCommand.java
  src/main/java/seedu/exchangecoursemapper/command/ListPersonalTrackerCommand.java
Labels: type.Task, priority.Low, severity.Low

#360 Update PPP to meet requirements based on latest changes
  docs/team/wahkia.md
Labels: type.Task, priority.Low, severity.Low

#361 [Improvement] Minor typo fixes
  docs/UserGuide.md
  src/main/java/seedu/exchangecoursemapper/ExchangeCourseMapper.java
Labels: priority.Low

#362 [Improvement] Final updates on code
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/team/hzxnancy.md
  src/main/java/seedu/exchangecoursemapper/command/AddCoursesCommand.java
  src/main/java/seedu/exchangecoursemapper/command/CompareMappedCommand.java
  src/main/java/seedu/exchangecoursemapper/constants/Commands.java
  src/main/java/seedu/exchangecoursemapper/courses/Course.java
  src/main/java/seedu/exchangecoursemapper/storage/DataIntegrityChecker.java
  src/main/java/seedu/exchangecoursemapper/storage/FileHandler.java
  src/main/java/seedu/exchangecoursemapper/storage/Storage.java
Labels: type.Enhancement, priority.Medium, severity.Medium

#365 Fix hyperlinks for DG and UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Bug, priority.High, severity.Medium

#366 Update PPP to fit page limit
  docs/team/wahkia.md
Labels: type.Task, priority.Low, severity.Low

#369 Update DG manual testing section
  docs/DeveloperGuide.md
Labels: type.Bug, priority.Medium, severity.Medium

#371 [Improvement] Update Sequence diagrams
  docs/diagrams/FindCoursesCommand.puml
  docs/diagrams/HelpCommand.puml
  docs/diagrams/ListUniCoursesCommand.puml
  docs/images/FindCoursesCommand.png
  docs/images/HelpCommand.png
  docs/images/ListUniCoursesCommand.png
Labels: priority.High

#370 [Improvement] Update List school why it is implemented
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ObtainContactsCommand.puml
  docs/images/ObtainContactsCommand.png
Labels: priority.Medium

#372 Extract method to align with AddCoursesCommand seq diagram
  docs/DeveloperGuide.md
  src/main/java/seedu/exchangecoursemapper/command/AddCoursesCommand.java
  src/main/java/seedu/exchangecoursemapper/ui/UI.java
Labels: type.Bug, priority.Medium, severity.Low

#373 [Improvement] Display Image on DG
  docs/diagrams/ObtainContactsCommand.puml
  docs/images/ObtainContactsCommand.png
Labels: priority.Low
